
"""Add to payroll_payments paid_by column

Revision ID: 26732c22af98
Revises: 2a39b7cae309
Create Date: 2025-10-06 12:05:36.538956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26732c22af98'
down_revision = '2a39b7cae309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        # REMOVED: Constraint operations that are causing issues
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        # REMOVED: Constraint operations that are causing issues
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('paid_by')

    # ### end Alembic commands ###