
"""Fix messages table columns

Revision ID: 2a39b7cae309
Revises: 98521e8cc4d3
Create Date: 2025-10-05 17:55:12.693074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a39b7cae309'
down_revision = '98521e8cc4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delivered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=True))
        # FIXED: Added constraint name
        batch_op.create_foreign_key('fk_messages_conversation_id', 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        # FIXED: Using the same constraint name
        batch_op.drop_constraint('fk_messages_conversation_id', type_='foreignkey')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('edited')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('is_delivered')

    # ### end Alembic commands ###
