"""Add is_delivered to messages

Revision ID: 43d30eb52c1f
Revises: 26732c22af98
Create Date: 2025-10-06 13:52:49.676896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d30eb52c1f'
down_revision = '26732c22af98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        # If a previous failed batch operation left a temp table behind, remove it.
        try:
            bind.execute(sa.text("DROP TABLE IF EXISTS _alembic_tmp_payroll_payments"))
        except Exception:
            # best-effort cleanup; continue regardless
            pass

    # Create the foreign key in a best-effort, idempotent way. Some DBs will
    # raise if the constraint already exists, so catch exceptions.
    try:
        with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
            batch_op.create_foreign_key(
                'fk_payroll_payments_paid_by',  # Add a constraint name
                'user', 
                ['paid_by'], 
                ['id']
            )
    except Exception:
        # If it fails (constraint exists or other issue), skip -- the FK is
        # non-critical for the rest of the migration steps here.
        pass

    # Add the actual messages columns that were intended, but only if
    # they don't already exist (prevents duplicate-column errors on re-run).
    bind = op.get_bind()
    msgs_cols = []
    if bind.dialect.name == 'sqlite':
        try:
            res = bind.execute(sa.text("PRAGMA table_info('messages')")).fetchall()
            msgs_cols = [r[1] for r in res]
        except Exception:
            msgs_cols = []

    with op.batch_alter_table('messages', schema=None) as batch_op:
        if 'is_delivered' not in msgs_cols:
            try:
                batch_op.add_column(sa.Column('is_delivered', sa.Boolean(), nullable=True, server_default='false'))
            except Exception:
                pass
        if 'delivered_at' not in msgs_cols:
            try:
                batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
            except Exception:
                pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('is_delivered')

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payroll_payments_paid_by', type_='foreignkey')

    # ### end Alembic commands ###