"""Add is_delivered to messages

Revision ID: 43d30eb52c1f
Revises: 26732c22af98
Create Date: 2025-10-06 13:52:49.676896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d30eb52c1f'
down_revision = '26732c22af98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_payroll_payments_paid_by',  # Add a constraint name
            'user', 
            ['paid_by'], 
            ['id']
        )

    # Add the actual messages columns that were intended
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delivered', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('is_delivered')

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payroll_payments_paid_by', type_='foreignkey')

    # ### end Alembic commands ###