"""Increase patient column lengths for encrypted data

Revision ID: 8c3c37a21dd2
Revises: 5a764b784854
Create Date: 2025-09-28 20:31:16.823866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3c37a21dd2'
down_revision = '5a764b784854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=550),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=550),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=550),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=550),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(length=550),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('nok_name',
               existing_type=sa.VARCHAR(length=550),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('nok_contact',
               existing_type=sa.VARCHAR(length=550),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('nok_contact',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=550),
               existing_nullable=True)
        batch_op.alter_column('nok_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=550),
               existing_nullable=True)
        batch_op.alter_column('occupation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=550),
               existing_nullable=True)
        batch_op.alter_column('destination',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=550),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=550),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=550),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=550),
               existing_nullable=True)

    # ### end Alembic commands ###
