"""Add cascade delete to audit_logs

Revision ID: 98521e8cc4d3
Revises: 2f508ba29215
Create Date: 2025-10-03 11:30:35.910482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98521e8cc4d3'
down_revision = '2f508ba29215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
